create sequence sek1;
create sequence seq_ID_WOJ;
create sequence seq_ID_SAMOCHOD;
create sequence seq_ID_CZESC;
create sequence seq_ID_Klient;

CREATE TABLE CZESC
  (
    ID_CZESCI    NUMBER (5) NOT NULL ,
    NAZWA_CZESCI VARCHAR2 (50) NOT NULL ,
    CENA_CZESCI  NUMBER (10,2) NOT NULL ,
    --ILOSC_CZESCI NUMBER (5) NOT NULL,
    ID_SAMOCHODU NUMBER (5) NOT NULL
  ) ;
ALTER TABLE CZESC ADD CONSTRAINT CZESC_PK PRIMARY KEY ( ID_CZESCI ) ;


CREATE TABLE Faktura
  (
    ID_FAKTURY     NUMBER (5) NOT NULL ,
    DATA_FAKTURY   DATE NOT NULL ,
    WARTOC_FAKTURY NUMBER (10,2) NOT NULL ,
    ID_KLIENTA     NUMBER (5) NOT NULL
  ) ;
ALTER TABLE Faktura ADD CONSTRAINT Faktura_PK PRIMARY KEY ( ID_FAKTURY ) ;


CREATE TABLE Klient
  (
    ID_KLIENTA     NUMBER (5) NOT NULL ,
    IMIE           VARCHAR2 (50) NOT NULL ,
    NAZWISKO       VARCHAR2 (50) NOT NULL ,
    TELEFON        NUMBER (12) NOT NULL ,
    ID_WOJEWODZTWA NUMBER (5) NOT NULL
  ) ;
ALTER TABLE Klient ADD CONSTRAINT Klient_PK PRIMARY KEY ( ID_KLIENTA ) ;


CREATE TABLE POZ_FAKTURY
  (
    POZYCJA     NUMBER (5) NOT NULL ,
    ID_FAKTURY  NUMBER (5) NOT NULL ,
    LICZBA      NUMBER (5) NOT NULL ,
    CENA_ZAKUPU NUMBER (10,2) NOT NULL ,
    ID_CZESCI   NUMBER (5) NOT NULL
  ) ;
ALTER TABLE POZ_FAKTURY ADD CONSTRAINT POZ_FAKTURY_PK PRIMARY KEY ( POZYCJA, ID_FAKTURY ) ;


CREATE TABLE SAMOCHOD
  (
    ID_SAMOCHODU NUMBER (5) NOT NULL ,
    MARKA_SAMOCHODU        VARCHAR2 (25) NOT NULL,
    MODEL_SAMOCHODU     VARCHAR2 (25) NOT NULL
  ) ;
ALTER TABLE SAMOCHOD ADD CONSTRAINT SAMOCHOD_PK PRIMARY KEY ( ID_SAMOCHODU ) ;


CREATE TABLE WOJEWODZTWO
  (
    ID_WOJEWODZTWA NUMBER (5) NOT NULL ,
    WOJEWODZTWO    VARCHAR2 (50) NOT NULL
  ) ;
ALTER TABLE WOJEWODZTWO ADD CONSTRAINT WOJEWODZTWO_PK PRIMARY KEY ( ID_WOJEWODZTWA ) ;


ALTER TABLE CZESC ADD CONSTRAINT CZESC_SAMOCHOD_FK FOREIGN KEY ( ID_SAMOCHODU ) REFERENCES SAMOCHOD ( ID_SAMOCHODU ) ;

ALTER TABLE Faktura ADD CONSTRAINT Faktura_Klient_FK FOREIGN KEY ( ID_KLIENTA ) REFERENCES Klient ( ID_KLIENTA ) ;

ALTER TABLE Klient ADD CONSTRAINT Klient_WOJEWODZTWO_FK FOREIGN KEY ( ID_WOJEWODZTWA ) REFERENCES WOJEWODZTWO ( ID_WOJEWODZTWA ) ;

ALTER TABLE POZ_FAKTURY ADD CONSTRAINT POZ_FAKTURY_CZESC_FK FOREIGN KEY ( ID_CZESCI ) REFERENCES CZESC ( ID_CZESCI ) ;

ALTER TABLE POZ_FAKTURY ADD CONSTRAINT POZ_FAKTURY_Faktura_FK FOREIGN KEY ( ID_FAKTURY ) REFERENCES Faktura ( ID_FAKTURY ) ;
